baseURL = "https://blog.lp-folio.fr/"
languageCode = "fr-fr"
title = "Mon Blog - Léo PROUDHOM"
theme = "PaperMod"          
contentDir = "Articles"
enableRobotsTXT = true

[pagination]
  pagerSize = 10


[params]
  author = "Léo PROUDHOM"
  description = "Un blog de technologies"
