name: Déploiement sur GitHub Pages (Hugo)

on:
  push:
    branches:
      - hugo
    paths:
      - 'Articles/**'
      - 'layouts/**'
      - 'config.*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Clean public directory
        run: rm -rf public

      - name: Build Hugo site
        run: hugo --minify --gc

      - name: Create .nojekyll file
        run: touch public/.nojekyll

      - name: Verify public directory contents
        run: ls -la public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: blog.lp-folio.fr
