name: Déploiement sur GitHub Pages (Hugo)

on:
  push:
    branches:
      - hugo   # déclenche quand tu pushes sur la branche hugo
  workflow_dispatch: # déclenche manuellement si besoin

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: blog.lp-folio.fr
